### ISSUE TITLE
@

### ISSUE THREAD

**Issue by Hayabusa636** [luckygambet/DD#1]
Could you update it for multiplayer? That would be awesome. Also do you have a menu for DDA? (Dungeon Defenders Awakened)

**Comment by luckygambet** [comment]
If you comment out line 3165 to line 3168
`		
if (heroManager->bRankedRemoteConnectionActive)
		{
			crashObj->NearMoveTarget();
		}
`
and recompile it will work on ranked. i dont have an account that is unbanned so i dont know if it gets past all the anticheat so use it at your own risk.
 
as for a DDA menu i do not have one

**Comment by Hayabusa636** [comment]
> If you comment out line 3165 to line 3168 ` if (heroManager->bRankedRemoteConnectionActive) { crashObj->NearMoveTarget(); } ` and recompile it will work on ranked. i dont have an account that is unbanned so i dont know if it gets past all the anticheat so use it at your own risk.
> 
> as for a DDA menu i do not have one

After commenting lines 3165 to 3168, I built it then got some errors. pic : https://i.upload.systems/udJ4xbnj
Build started...
1>------ Build started: Project: DDModMenuReduxByButter, Configuration: Debug x64 ------
1>dllmain.cpp
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SdkHeaders.h(20,43): warning C4311: 'type cast': pointer truncation from 'HMODULE' to 'DWORD'
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SdkHeaders.h(20,43): warning C4302: 'type cast': truncation from 'HMODULE' to 'DWORD'
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SdkHeaders.h(121,1): warning C4312: 'type cast': conversion from 'DWORD' to 'TArray<FNameEntry *> *' of greater size
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SdkHeaders.h(141,1): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SdkHeaders.h(153,1): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SDK_HEADERS\Core_functions.h(27,66): warning C4312: 'type cast': conversion from 'DWORD' to 'TArray<UObject *> *' of greater size
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\Header.h(22,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory
1>HelperFunctions.cpp
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(11,32): warning C4311: 'type cast': pointer truncation from 'void *' to 'DWORD'
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(11,32): warning C4302: 'type cast': truncation from 'void *' to 'DWORD'
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(11,46): warning C4311: 'type cast': pointer truncation from 'void *' to 'DWORD'
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(11,46): warning C4302: 'type cast': truncation from 'void *' to 'DWORD'
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(14,25): warning C4311: 'type cast': pointer truncation from 'void *' to 'DWORD'
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(14,25): warning C4302: 'type cast': truncation from 'void *' to 'DWORD'
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(14,30): warning C4312: 'type cast': conversion from 'DWORD' to 'DWORD *' of greater size
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(46,39): warning C4309: '=': truncation of constant value
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(61,11): warning C4018: '<': signed/unsigned mismatch
1>Hooking.cpp
1>imgui.cpp
1>imgui_demo.cpp
1>imgui_draw.cpp
1>imgui_impl_dx9.cpp
1>imgui_impl_win32.cpp
1>imgui_widgets.cpp
1>Generating Code...
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(29): warning C4715: 'HookAddr64': not all control paths return a value
1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(16): warning C4715: 'HookAddr32': not all control paths return a value
1>Done building project "DDModMenuByButter.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

How do I fix?

**Comment by luckygambet** [comment]
> > If you comment out line 3165 to line 3168 `if (heroManager->bRankedRemoteConnectionActive) { crashObj->NearMoveTarget(); }` and recompile it will work on ranked. i dont have an account that is unbanned so i dont know if it gets past all the anticheat so use it at your own risk.
> > as for a DDA menu i do not have one
> 
> After commenting lines 3165 to 3168, I built it then got some errors. pic : https://i.upload.systems/udJ4xbnj Build started... 1>------ Build started: Project: DDModMenuReduxByButter, Configuration: Debug x64 ------ 1>dllmain.cpp 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SdkHeaders.h(20,43): warning C4311: 'type cast': pointer truncation from 'HMODULE' to 'DWORD' 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SdkHeaders.h(20,43): warning C4302: 'type cast': truncation from 'HMODULE' to 'DWORD' 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SdkHeaders.h(121,1): warning C4312: 'type cast': conversion from 'DWORD' to 'TArray<FNameEntry *> *' of greater size 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SdkHeaders.h(141,1): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SdkHeaders.h(153,1): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SDK_HEADERS\Core_functions.h(27,66): warning C4312: 'type cast': conversion from 'DWORD' to 'TArray<UObject *> *' of greater size 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\Header.h(22,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory 1>HelperFunctions.cpp 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(11,32): warning C4311: 'type cast': pointer truncation from 'void *' to 'DWORD' 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(11,32): warning C4302: 'type cast': truncation from 'void *' to 'DWORD' 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(11,46): warning C4311: 'type cast': pointer truncation from 'void *' to 'DWORD' 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(11,46): warning C4302: 'type cast': truncation from 'void *' to 'DWORD' 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(14,25): warning C4311: 'type cast': pointer truncation from 'void *' to 'DWORD' 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(14,25): warning C4302: 'type cast': truncation from 'void *' to 'DWORD' 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(14,30): warning C4312: 'type cast': conversion from 'DWORD' to 'DWORD *' of greater size 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(46,39): warning C4309: '=': truncation of constant value 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(61,11): warning C4018: '<': signed/unsigned mismatch 1>Hooking.cpp 1>imgui.cpp 1>imgui_demo.cpp 1>imgui_draw.cpp 1>imgui_impl_dx9.cpp 1>imgui_impl_win32.cpp 1>imgui_widgets.cpp 1>Generating Code... 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(29): warning C4715: 'HookAddr64': not all control paths return a value 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(16): warning C4715: 'HookAddr32': not all control paths return a value 1>Done building project "DDModMenuByButter.vcxproj" -- FAILED. ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
> 
> How do I fix?

fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory


you need the windows direct x sdk you should be able to get the from here
[https://www.microsoft.com/en-us/download/details.aspx?id=6812](url)

**Comment by Hayabusa636** [comment]
> > > If you comment out line 3165 to line 3168 `if (heroManager->bRankedRemoteConnectionActive) { crashObj->NearMoveTarget(); }` and recompile it will work on ranked. i dont have an account that is unbanned so i dont know if it gets past all the anticheat so use it at your own risk.
> > > as for a DDA menu i do not have one
> > 
> > 
> > After commenting lines 3165 to 3168, I built it then got some errors. pic : https://i.upload.systems/udJ4xbnj Build started... 1>------ Build started: Project: DDModMenuReduxByButter, Configuration: Debug x64 ------ 1>dllmain.cpp 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SdkHeaders.h(20,43): warning C4311: 'type cast': pointer truncation from 'HMODULE' to 'DWORD' 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SdkHeaders.h(20,43): warning C4302: 'type cast': truncation from 'HMODULE' to 'DWORD' 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SdkHeaders.h(121,1): warning C4312: 'type cast': conversion from 'DWORD' to 'TArray<FNameEntry *> *' of greater size 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SdkHeaders.h(141,1): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SdkHeaders.h(153,1): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\SDK_HEADERS\Core_functions.h(27,66): warning C4312: 'type cast': conversion from 'DWORD' to 'TArray<UObject *> *' of greater size 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\Header.h(22,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory 1>HelperFunctions.cpp 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(11,32): warning C4311: 'type cast': pointer truncation from 'void *' to 'DWORD' 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(11,32): warning C4302: 'type cast': truncation from 'void *' to 'DWORD' 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(11,46): warning C4311: 'type cast': pointer truncation from 'void *' to 'DWORD' 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(11,46): warning C4302: 'type cast': truncation from 'void *' to 'DWORD' 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(14,25): warning C4311: 'type cast': pointer truncation from 'void *' to 'DWORD' 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(14,25): warning C4302: 'type cast': truncation from 'void *' to 'DWORD' 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(14,30): warning C4312: 'type cast': conversion from 'DWORD' to 'DWORD *' of greater size 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(46,39): warning C4309: '=': truncation of constant value 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(61,11): warning C4018: '<': signed/unsigned mismatch 1>Hooking.cpp 1>imgui.cpp 1>imgui_demo.cpp 1>imgui_draw.cpp 1>imgui_impl_dx9.cpp 1>imgui_impl_win32.cpp 1>imgui_widgets.cpp 1>Generating Code... 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(29): warning C4715: 'HookAddr64': not all control paths return a value 1>C:\Users\Michael\Downloads\DD-main\DD-main\DDModMenuByButter\HelperFunctions.cpp(16): warning C4715: 'HookAddr32': not all control paths return a value 1>Done building project "DDModMenuByButter.vcxproj" -- FAILED. ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
> > How do I fix?
> 
> fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory
> 
> you need the windows direct x sdk you should be able to get the from here [https://www.microsoft.com/en-us/download/details.aspx?id=6812](url)

I downloaded the sdk you linked and at the end up setup I got setup failed error code S1023 this means I already have a newer version of the visual C++ 2010. Should I uninstall all the newer visual C++ 2010 and install the one you linked or try something else. Thanks!

**Comment by luckygambet** [comment]
Yes try that and report back if you are still having problems

**Comment by Hayabusa636** [comment]
> Yes try that and report back if you are still having problems

SDK install went through, installed the updated sdk's after and that went good also. Went to build and got this https://i.upload.systems/cqTZkY4Y

Build started...
1>------ Build started: Project: DDModMenuReduxByButter, Configuration: Debug x64 ------
1>dllmain.cpp
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\SdkHeaders.h(20,43): warning C4311: 'type cast': pointer truncation from 'HMODULE' to 'DWORD'
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\SdkHeaders.h(20,43): warning C4302: 'type cast': truncation from 'HMODULE' to 'DWORD'
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\SdkHeaders.h(121,1): warning C4312: 'type cast': conversion from 'DWORD' to 'TArray<FNameEntry *> *' of greater size
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\SdkHeaders.h(141,1): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\SdkHeaders.h(153,1): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\SDK_HEADERS\Core_functions.h(27,66): warning C4312: 'type cast': conversion from 'DWORD' to 'TArray<UObject *> *' of greater size
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\Header.h(22,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory
1>imgui_widgets.cpp
1>Generating Code...
1>Done building project "DDModMenuByButter.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by luckygambet** [comment]
Can you verify for me if you have these in your project settings
https://stackoverflow.com/questions/17015088/missing-files-directx-sdk-d3dx9-lib-d3dx9-h

**Comment by Hayabusa636** [comment]
> 

Here is the comparison https://i.upload.systems/jABPwauq

**Comment by Hayabusa636** [comment]
> > 
> 
> Here is the comparison https://i.upload.systems/jABPwauq

edit win32 https://i.upload.systems/gck2Zrz4

**Comment by luckygambet** [comment]
ensure that you are compiling to x86.
check your system variables for DXSDK_DIR : C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\

**Comment by Hayabusa636** [comment]
here's what I found to that path : https://i.upload.systems/pshJB85U
Figured out I was building to 64, changed to 86 and got this : https://i.upload.systems/rflJcd8F

Build started...
1>------ Build started: Project: DDModMenuReduxByButter, Configuration: Debug Win32 ------
1>dllmain.cpp
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1172,49): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1173,49): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1174,49): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1175,51): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1176,51): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1177,51): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1853,6): warning C4804: '>=': unsafe use of type 'bool' in operation
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1884,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1885,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1886,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1888,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1889,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1890,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1892,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1893,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1894,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(2425,57): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(2427,57): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(2428,64): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(3050,12): warning C4244: 'argument': conversion from 'time_t' to 'unsigned int', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(3165,19): fatal error C1012: unmatched parenthesis: missing ')'
1>HelperFunctions.cpp
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\HelperFunctions.cpp(46,39): warning C4309: '=': truncation of constant value
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\HelperFunctions.cpp(61,11): warning C4018: '<': signed/unsigned mismatch
1>Hooking.cpp
1>imgui.cpp
1>imgui_demo.cpp
1>imgui_draw.cpp
1>imgui_impl_dx9.cpp
1>imgui_impl_win32.cpp
1>imgui_widgets.cpp
1>Generating Code...
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\HelperFunctions.cpp(16): warning C4715: 'HookAddr32': not all control paths return a value
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\HelperFunctions.cpp(29): warning C4715: 'HookAddr64': not all control paths return a value
1>Done building project "DDModMenuByButter.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by luckygambet** [comment]
make sure it looks like this
[https://imgur.com/O21vN2d](url)
that error means there is something wrong with ")"

**Comment by Hayabusa636** [comment]
> make sure it looks like this [https://imgur.com/O21vN2d](url) that error means there is something wrong with ")"

I used # instead of // to comment it xD
With that fixed I got 

Build started...
1>------ Build started: Project: DDModMenuReduxByButter, Configuration: Debug Win32 ------
1>dllmain.cpp
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1172,49): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1173,49): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1174,49): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1175,51): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1176,51): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1177,51): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1853,6): warning C4804: '>=': unsafe use of type 'bool' in operation
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1884,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1885,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1886,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1888,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1889,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1890,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1892,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1893,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1894,50): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(2425,57): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(2427,57): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(2428,64): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(3050,12): warning C4244: 'argument': conversion from 'time_t' to 'unsigned int', possible loss of data
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xstring(2575,23): warning C4244: 'argument': conversion from 'wchar_t' to 'const _Elem', possible loss of data
1>        with
1>        [
1>            _Elem=char
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xstring(2586): message : see reference to function template instantiation 'void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<wchar_t*>(_Iter,const _Iter,std::input_iterator_tag)' being compiled
1>        with
1>        [
1>            _Iter=wchar_t *
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xstring(2586): message : see reference to function template instantiation 'void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<wchar_t*>(_Iter,const _Iter,std::input_iterator_tag)' being compiled
1>        with
1>        [
1>            _Iter=wchar_t *
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xstring(2566): message : see reference to function template instantiation 'void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<wchar_t*>(const _Iter,const _Iter,std::forward_iterator_tag)' being compiled
1>        with
1>        [
1>            _Iter=wchar_t *
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xstring(2566): message : see reference to function template instantiation 'void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<wchar_t*>(const _Iter,const _Iter,std::forward_iterator_tag)' being compiled
1>        with
1>        [
1>            _Iter=wchar_t *
1>        ]
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1248): message : see reference to function template instantiation 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string<std::_String_iterator<std::_String_val<std::_Simple_types<_Elem>>>,0>(_Iter,_Iter,const _Alloc &)' being compiled
1>        with
1>        [
1>            _Elem=wchar_t,
1>            _Iter=std::_String_iterator<std::_String_val<std::_Simple_types<wchar_t>>>,
1>            _Alloc=std::allocator<char>
1>        ]
1>C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\dllmain.cpp(1248): message : see reference to function template instantiation 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string<std::_String_iterator<std::_String_val<std::_Simple_types<_Elem>>>,0>(_Iter,_Iter,const _Alloc &)' being compiled
1>        with
1>        [
1>            _Elem=wchar_t,
1>            _Iter=std::_String_iterator<std::_String_val<std::_Simple_types<wchar_t>>>,
1>            _Alloc=std::allocator<char>
1>        ]
1>imgui_widgets.cpp
1>Generating Code...
1>DDModMenuByButter.vcxproj -> C:\Users\Michael\Downloads\DD-main\Debug\DDModMenuReduxByButter.dll
1>Done building project "DDModMenuByButter.vcxproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Looks like it worked but how do I use it now? If it couldn't be more obvious, this is my first successful build lol. I'm guessing you just inject dll now and that's it?

**Comment by luckygambet** [comment]
yup just inject it and it will work. here is a video on how to inject it and find the correct dll 
[https://youtu.be/sMVKbTbhOU8?t=116](url)

**Comment by Hayabusa636** [comment]
> 

Thanks for all the help.
I don't understand how to get the dll I mean I see the dllmain but its .cpp not dll so I can't inject. The video you linked seems helpful but as someone that knows no coding (hopefully I learn it in the future because I find it interesting but very complicated)  it's over my head. If I have to do all those steps I think I have to pass then. Thank you again for helping though! Usually people don't like to help me as much as u did today.

**Comment by luckygambet** [comment]
when you open the folder go up 1 folder so from this
\repos\DDModMenuByButterRedux\DDModMenuByButter
to this 
\repos\DDModMenuByButterRedux
and you find a new folder called release or debug and the dll is in there

**Comment by luckygambet** [comment]
no problem you always have the source code to mess around with and learn or you can just ignore it and use the menu

**Comment by Hayabusa636** [comment]
> when you open the folder go up 1 folder so from this \repos\DDModMenuByButterRedux\DDModMenuByButter to this \repos\DDModMenuByButterRedux and you find a new folder called release or debug and the dll is in there

I went to C:\Users\Michael\Downloads\DD-main\DDModMenuByButter\Release and found DDModMenuReduxByButter.dll.receipe (.recipe might of not been it I can't remember) so I removed the .recipe to make it a dll 
inject didnt work so I looked at the dll and only thing inside is 

<?xml version="1.0" encoding="utf-8"?>
<Project>
  <ProjectOutputs>C:\Users\Dakota\source\repos\DDModMenuByButterRedux\Release\DDModMenuReduxByButter.dll</ProjectOutputs>
  <ContentFiles></ContentFiles>
  <SatelliteDlls></SatelliteDlls>
  <NonRecipeFileRefs></NonRecipeFileRefs>
</Project>

your path has redux while mine is different  : https://i.upload.systems/YYt5GpP9

**Comment by Hayabusa636** [comment]
I went to the path to what the dll says but nothing is there for me if that means anything https://i.upload.systems/ZcVdq0kx

**Comment by luckygambet** [comment]
in your DD-main folder you should look like this after compiling 
[https://i.imgur.com/KqbpeLy.png](url)
and in the release or debug folder should be the dll

**Comment by luckygambet** [comment]
it should be in this folder
C:\Users\Michael\Downloads\DD-main\Debug\ according to your build output

**Comment by Hayabusa636** [comment]
> 

It finally works though I have one issue, when I inject it, I cant select anything with my mouse. As in if I press esc my left click wont register and I cant click resume game. Weird because left click works in game to attack but not when I open up a menu.
Another explanation when I press e to open forge, I can select any of the options, I have to press esc to get out

**Comment by Hayabusa636** [comment]
Another bug I found, it randomly disconnects if someone else is in lobby. So I could start wave and seconds later it disconnects and I have to reinject.

**Comment by Hayabusa636** [comment]
Works great so far. Is it possible to add an item quality option for autoloot? Like if I set it to ult, it picks up anything ult or higher no matter the stats. Also a minimum upgrade number for an item autoloot setting would be cool too.

**Comment by luckygambet** [comment]
It is possible but i have stopped working on this project i dont have the time to update it

**Comment by Hayabusa636** [comment]
> It is possible but i have stopped working on this project i dont have the time to update it

Aw okay. Understandable
