### ISSUE TITLE
Compatibility 

### ISSUE THREAD

**Issue by Hayabusa636** [luckygambet/DD#2]
Hey butter! Long time no see. I was wondering if this will work with the vanilla game as they are currently doing updates to it and putting off redux for now. Thanks for the help!

**Comment by luckygambet** [comment]
Hey. this will work for the vanilla game with a few updates but i have been quite busy IRL too update the mod menu when i find the time and get everything working i will release a video on my youtube channel with the download link.

**Comment by Hayabusa636** [comment]
> Hey. this will work for the vanilla game with a few updates but i have been quite busy IRL too update the mod menu when i find the time and get everything working i will release a video on my youtube channel with the download link.

Hey thanks for the reply! You don't even have to make a video if you can link it here. Saves the hassle. Can't wait to play again!

**Comment by luckygambet** [comment]
new update is out you can find it on my youtube channel. ill release the source code soon
