### ISSUE TITLE
New update yey!

### ISSUE THREAD

**Issue by Hayabusa636** [luckygambet/DD#3]
Hey man long time no write. Dungeon defenders just got a new update! With new maps and even a new hero! Sadly your latest release doesn't work with this update. Could you make it compatible for me? I cant wait to try some things with this new hero. :D

**Comment by luckygambet** [comment]
Here have fun. I only updated to finish the new map. I did no testing to see if everything still works. if there are any bugs just post here and when i get the time i will fix it 
heres the download link. you need an injector. cheat engine works fine for injecting.
https://www.mediafire.com/file/ie5ziieuv6ito98/DDModMenuByButter.zip/file

**Comment by Hayabusa636** [comment]
Thanks man. You a real one for this update. Ill see if I kind find any bugs.

**Comment by Hayabusa636** [comment]
> Here have fun. I only updated to finish the new map. I did no testing to see if everything still works. if there are any bugs just post here and when i get the time i will fix it heres the download link. you need an injector. cheat engine works fine for injecting. https://www.mediafire.com/file/ie5ziieuv6ito98/DDModMenuByButter.zip/file

I have found that they have fixed autokill with the most recent patch 9.2.2 ( :( ) I have also found that when using the "give" option on an item, when relaunching the game the item will change in appearance. ex: I used give on this rainmaker and upon relaunching the game, it has changed to this default model. Although stats have stayed the same. pic: https://i.upload.systems/IoO97RQk

**Comment by luckygambet** [comment]
What map and difficulty are you doing. When i get time i till try and reproduce this and fix it.

**Comment by Hayabusa636** [comment]
> What map and difficulty are you doing. When i get time i till try and reproduce this and fix it.

Alr bet, It seems its fixed outright though. I've tried 5 maps and autokill, lootshower, autopickup  doesn't work on any of them. Teleport players seems broken as well.

**Comment by luckygambet** [comment]
I have done a quick update to fix auto kill lootshower and auto pickup. As for item duplication if this update did not fix it, it will take a while longer to fix.
https://www.mediafire.com/file/du1ztt2m8yb3218/DDModMenuByButter.zip/file

**Comment by Hayabusa636** [comment]
> I have done a quick update to fix auto kill lootshower and auto pickup. As for item duplication if this update did not fix it, it will take a while longer to fix. https://www.mediafire.com/file/du1ztt2m8yb3218/DDModMenuByButter.zip/file

wow that was fast! Although I have just tested and it still does not work on my end. Heres a video. Autokill, Autopickup, Lootshower broken. https://streamable.com/s7odst

**Comment by luckygambet** [comment]
Strange try and verify integrity of game files and see if that fixes the problem.
https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB

**Comment by Hayabusa636** [comment]
> Strange try and verify integrity of game files and see if that fixes the problem. https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB

Tried this. Still the same weird.

**Comment by Hayabusa636** [comment]
> > Strange try and verify integrity of game files and see if that fixes the problem. https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB
> 
> Tried this. Still the same weird.

they are both the same size, did you reupload the same one?

**Comment by luckygambet** [comment]
Lol yea that happens sometimes i will introduce something in the future to know what dll update your are using when injected
